### ISSUE TITLE
github action madness

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidySummarizedExperiment#12]
Hello @mblue9,

when you have time do you think you can have a look to github action for Mac

```
Error: Refusing to uninstall /usr/local/Cellar/curl/7.73.0_1
because it is required by php, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies curl
```

**Comment by mblue9** [comment]
Let's see if changing to `brew uninstall --ignore-dependencies curl` here https://github.com/stemangiola/tidySummarizedExperiment/pull/13 fixes it
