### ISSUE TITLE
Error: Key columns are missing. A data frame is returned for independent data analysis

### ISSUE THREAD

**Issue by epruesse** [stemangiola/tidySummarizedExperiment#42]
I'm getting 

```
Key columns are missing. A data frame is returned for independent data analysis
```

when I do a `select()`. It's not clear to me what that means or how I should prevent it.

**Comment by stemangiola** [comment]
close for inactivity, let me know if this is still a problem.

**Comment by stemangiola** [comment]
Hello @william-hutchison, can we please change this message in tidyseurat/SE/SCE? It is obviously not as clear to what is happening.

For example is tidySE it would be something like

tidySummarizedExperiment says: Your operation dropped essential columns like .feature or .sample. This creates a non-valid `SummarizedExperiment`. Therefore, a data frame is returned for your to carry independent data analysis.
