### ISSUE TITLE
mutate() shifts order of data

### ISSUE THREAD

**Issue by mikelove** [stemangiola/tidySummarizedExperiment#66]
It appears that `mutate()` shifts the order of data. Note the correspondence of counts and new_counts below, in the second piped operation:

```
library(tidySummarizedExperiment)
pasilla_tidy <- tidySummarizedExperiment::pasilla

pasilla_tidy %>%
  filter(.feature == "FBgn0000008")

 # A SummarizedExperiment-tibble abstraction: 7 × 7
 # Features=1 | Samples=7 | Assays=counts
   .feature    .sample counts condition type
   <chr>       <chr>    <int> <chr>     <chr>
 1 FBgn0000008 untrt1      92 untreated single_end
 2 FBgn0000008 untrt2     161 untreated single_end
 3 FBgn0000008 untrt3      76 untreated paired_end
 4 FBgn0000008 untrt4      70 untreated paired_end
 5 FBgn0000008 trt1       140 treated   single_end
 6 FBgn0000008 trt2        88 treated   paired_end
 7 FBgn0000008 trt3        70 treated   paired_end

pasilla_tidy %>%
  mutate(new_counts = counts + 1) %>%
  filter(.feature == "FBgn0000008") 

# A SummarizedExperiment-tibble abstraction: 7 × 7
 # Features=1 | Samples=7 | Assays=counts, new_counts
   .feature    .sample counts new_counts condition type
   <chr>       <chr>    <int>      <dbl> <chr>     <chr>
 1 FBgn0000008 untrt1      92        141 untreated single_end
 2 FBgn0000008 untrt2     161         89 untreated single_end
 3 FBgn0000008 untrt3      76         71 untreated paired_end
 4 FBgn0000008 untrt4      70         93 untreated paired_end
 5 FBgn0000008 trt1       140        162 treated   single_end
 6 FBgn0000008 trt2        88         77 treated   paired_end
 7 FBgn0000008 trt3        70         71 treated   paired_end
```

Expected behaviour is recovered with tidybulk:

```
library(tidybulk)
pasilla_tidy %>%
   tidybulk() %>%
   mutate(new_counts = counts + 1) %>%
   filter(.feature == "FBgn0000008")

 # A tibble: 7 × 6
   .feature    .sample counts condition type       new_counts
   <chr>       <chr>    <int> <chr>     <chr>           <dbl>
 1 FBgn0000008 untrt1      92 untreated single_end         93
 2 FBgn0000008 untrt2     161 untreated single_end        162
 3 FBgn0000008 untrt3      76 untreated paired_end         77
 4 FBgn0000008 untrt4      70 untreated paired_end         71
 5 FBgn0000008 trt1       140 treated   single_end        141
 6 FBgn0000008 trt2        88 treated   paired_end         89
 7 FBgn0000008 trt3        70 treated   paired_end         71
```

```
 R version 4.2.2 (2022-10-31)
 Platform: aarch64-apple-darwin20 (64-bit)
 Running under: macOS Ventura 13.0.1

 Matrix products: default
 BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
 LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

 locale:
 [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

 attached base packages:
 [1] stats4    stats     graphics  grDevices datasets  utils     methods   base

 other attached packages:
  [1] tidySummarizedExperiment_1.8.0 SummarizedExperiment_1.28.0    Biobase_2.58.0
  [4] GenomicRanges_1.50.2           GenomeInfoDb_1.34.9            IRanges_2.32.0
  [7] S4Vectors_0.36.1               BiocGenerics_0.44.0            MatrixGenerics_1.10.0
 [10] matrixStats_0.63.0             pkgdown_2.0.7                  testthat_3.1.6
 [13] rmarkdown_2.20                 devtools_2.4.5                 usethis_2.1.6
```

**Comment by stemangiola** [comment]
> It appears that `mutate()` shifts the order of data. Note the correspondence of counts and new_counts below, in the second piped operation:


This emerges because you are creating a new assay column (in contrast to creating another gene or sample metadata column). The reason of this specific behaviour is that the tibble is abstracted querying for resources with this order from the `SummarizedExperiment`

1) rownames
2) colnames
3) assays
4) metadata

The order of abstracted columns is not saved (in the metadata is, but that is an actual table)

> Expected behaviour is recovered with tidybulk:

If you convert the `SummarizedExperiment` into a `tibble` with `tidybulk()`, then the tibble is not an abstraction, but it is an actual `data.frame`

**Comment by mikelove** [comment]
Before I close, I take it that creating new assay data this way is not recommended then?

I kind of like the flexibility of defining new columns on the fly this way, especially for EDA.

**Comment by stemangiola** [comment]
> Before I close, I take it that creating new assay data this way is not recommended then?

I don't see it as a problem, it is just another matrix in the `SummarizedExperiment` that you can use for analysis or plotting. Tidyverse think it is simply another column. 

As a note, if you use it for plotting, probably defining `count + 1` in the `aes()` it would better in my opinion. But if you use this quantity multiple times and you want to define it once, why not.

> I kind of like the flexibility of defining new columns on the fly this way, especially for EDA.

Are you referring you like the flexibility of a tibble? For all purposes, I don't think `SummarizedExperiment` and `tibble` as two different things anymore, it's just that  `SummarizedExperiment` compresses the data better, and interfaces with Bioconductor. 

Having said that, yes the tibble has no constrain, which I still use for non-standard analyses, but I tend to stick to `SummarizedExperiment` container normally. If you prefer to use tibble I don't see any problem.

**Comment by mikelove** [comment]
Is there a way to create a new matrix for a tidySE using `mutate()` and later pull it out, in a way that it would be ordered?

**Comment by stemangiola** [comment]
You mean something like

```r
N = 4
tidySummarizedExperiment::pasilla |> 
mutate(counts_2 = counts) |> 
pull(N)
```

In this case, yes it is not easy to assume what `N` is before you print the object on screen. 

But unless you have a pretty specific need, I stopped using numerical indexes to subset objects as `tidyverse` select options are so powerful you don't need it anymore. This made my code so much more robust.

**Comment by mikelove** [comment]
I mean, this seems like you don't want people doing these `mutate()` operations on the assay, or they will get confused:

```
> x <- tidySummarizedExperiment::pasilla |> mutate(counts_2 = counts)
> assays(x)[[1]][1:5,1:5]
            untrt1 untrt2 untrt3 untrt4 trt1
FBgn0000003      0      0      0      0    0
FBgn0000008     92    161     76     70  140
FBgn0000014      5      1      0      0    4
FBgn0000015      0      2      1      2    1
FBgn0000017   4664   8714   3564   3150 6205
> assays(x)[[2]][1:5,1:5]
            untrt1 untrt2 untrt3 untrt4 trt1
FBgn0000003      0      0      1      0    0
FBgn0000008    140     88     70     92  161
FBgn0000014      4      0      0      5    1
FBgn0000015      1      0      0      0    2
FBgn0000017   6205   3072   3334   4664 8714
```

**Comment by stemangiola** [comment]
Gees I was looking at this now, this is not good. I have to correct this behaviour.

**Comment by mikelove** [comment]
To clarify, this is what i meant by shifts:

<img width="145" alt="Screenshot 2023-03-13 at 9 52 47 PM" src="https://user-images.githubusercontent.com/69203/224872006-d0897146-7e0b-481c-b9c4-018f50ac596a.png">

**Comment by stemangiola** [comment]
I completely missed this initial point of yours XD  It was clear from your post.

**Comment by stemangiola** [comment]
> pasilla_tidy %>%
>   mutate(new_counts = counts + 1) %>%
>   filter(.feature == "FBgn0000008")

This what I get now, I will merge soon

```r
> library(tidySummarizedExperiment)
> pasilla_tidy <- tidySummarizedExperiment::pasilla
> 
> pasilla_tidy %>%
+     filter(.feature == "FBgn0000008")
# A SummarizedExperiment-tibble abstraction: 7 × 5
# Features=1 | Samples=7 | Assays=counts
  .feature    .sample counts condition type      
  <chr>       <chr>    <int> <chr>     <chr>     
1 FBgn0000008 untrt1      92 untreated single_end
2 FBgn0000008 untrt2     161 untreated single_end
3 FBgn0000008 untrt3      76 untreated paired_end
4 FBgn0000008 untrt4      70 untreated paired_end
5 FBgn0000008 trt1       140 treated   single_end
6 FBgn0000008 trt2        88 treated   paired_end
7 FBgn0000008 trt3        70 treated   paired_end
> pasilla_tidy %>%
+     mutate(new_counts = counts + 1) %>%
+     filter(.feature == "FBgn0000008") 
# A SummarizedExperiment-tibble abstraction: 7 × 6
# Features=1 | Samples=7 | Assays=counts, new_counts
  .feature    .sample counts new_counts condition type      
  <chr>       <chr>    <int>      <dbl> <chr>     <chr>     
1 FBgn0000008 untrt1      92         93 untreated single_end
2 FBgn0000008 untrt2     161        162 untreated single_end
3 FBgn0000008 untrt3      76         77 untreated paired_end
4 FBgn0000008 untrt4      70         71 untreated paired_end
5 FBgn0000008 trt1       140        141 treated   single_end
6 FBgn0000008 trt2        88         89 treated   paired_end
7 FBgn0000008 trt3        70         71 treated   paired_end
```

**Comment by stemangiola** [comment]
This problem should be fixed in the new github version. 

Thanks for pointing this out!
