### ISSUE TITLE
unnesting on RangedSummarizedExperiment cols

### ISSUE THREAD

**Issue by mikelove** [stemangiola/tidySummarizedExperiment#68]
We had previously discussed nesting/unnesting for RSE, e.g. here https://gist.github.com/mikelove/40b6882ff88f31b7ccb847530022b058

I think this is not merged into the devel branch? Nesting is not a problem, but unnest with v1.9.5 gives

```
 > se <- se %>%
 + nest(data = -.feature) %>%
 + mutate(rho = map_dbl(data, ~cor(pull(.x, x), pull(.x, y)))) %>%
!+ unnest(data)
 Error in `list_sizes()`:
 ! `x[[1]]` must be a vector, not a <RangedSummarizedExperiment> object.
```

I was going to show an example for workshops this summer that unnests at a step like this. I could just drop the ranges to make it work with current release.

But long term it would be great to support the ranged case.

**Comment by stemangiola** [comment]
> Nesting is not a problem, but unnest with v1.9.5 gives

Was I working on this issue? I don't recall now, but I agree this should be solved. Did you provide me in the past with a reproducible example? (apologies if my memory fault)



> Or, thinking more on this, `unnest` can be an expensive operation (I'm seeing this even for small example datasets). Maybe I should just pass the information from the nested object back to the original object via another step.

While `nest` is elegant, it is quite slow indeed, left joining another summarised dataset could be a faster option, although less elegant.

**Comment by mikelove** [comment]
At the link above you had already fixed in branch `adapt_to_rangedSE`.

Yeah, I think here I won't unnest. I'm currently comparing different approaches.

**Comment by stemangiola** [comment]
@william-hutchison do you want to have a look at this error?

**Comment by william-hutchison** [comment]
Sure, I will look into this now

**Comment by stemangiola** [comment]
> Sure, I will look into this now

if you need a reproducible example feel free to ask to @mikelove (apology if you give this to me in the past).
